plugins/contracts/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
#
match "trainees_payments/index" => "trainees_payments#index", :via => :get
match "projects/:project_id/contracts(/:contract_id)/payment_administrative" => "contracts#gerar_pagamentos_administrativo"
match "projects/:project_id/contracts(/:contract_id)/payment_intern" => "contracts#gerar_pagamentos"
get "provisionamentos/index"
match 'provisionamentos/gerar' => 'provisionamentos#importar', :via => :post
match 'projects/:project_id/contracts/:contract_id/payment' => 'contracts#contabilizar_pagamentos', :via => :post
match 'contracts/all'                                       => 'contracts#all',     :via => :get
match 'contracts/:id'                                       => 'contracts#destroy', :via => :delete
match 'contracts/:id/edit'                                  => 'contracts#edit',    :via => :get
match 'projects/:project_id/contracts'                      => 'contracts#index',   :via => :get
match 'projects/:project_id/contracts/new'                  => 'contracts#new',     :via => :get
match 'projects/:project_id/contracts/:id/edit'             => 'contracts#edit',    :via => :get
match 'projects/:project_id/contracts/:id'                  => 'contracts#show',    :via => :get
match 'projects/:project_id/contracts'                      => 'contracts#create',  :via => :post
match 'projects/:project_id/contracts/:id'                  => 'contracts#update',  :via => :put
match 'projects/:project_id/contracts/:id'                  => 'contracts#destroy', :via => :delete
match 'projects/:project_id/contracts/:id/add_time_entries' => 'contracts#add_time_entries', :via => :get
match 'projects/:project_id/contracts/:id/assoc_time_entries_with_contract' =>
        'contracts#assoc_time_entries_with_contract',
        :via => :put

plugins/contracts/app/models/contract.rb
class Contract < ActiveRecord::Base
  unloadable
  belongs_to :project 
  has_many   :time_entries
  validates_presence_of :title, :start_date, :end_date, :agreement_date, 
                        :purchase_amount, :hourly_rate, :project_id
  validates :title, :uniqueness => { :case_sensitive => false }
  #validates :start_date, :is_after_agreement_date => true
  validates :end_date, :is_after_start_date => true
  before_destroy { |contract| contract.time_entries.clear }

  def hours_purchased
    self.purchase_amount / self.hourly_rate
  end
  
  def hours_spent
    self.time_entries.sum { |time_entry| time_entry.hours }
  end

  def amount_spent
    self.time_entries.sum do |time_entry|
      amount = time_entry.cost
      if amount == 0
        amount = time_entry.hours * (Rate.amount_for(time_entry.user, project, time_entry.spent_on.strftime("%Y-%m-%d")) || self.hourly_rate)
	time_entry.cost = amount
        time_entry.save!
      end
      amount
    end
  end
  
  def amount_remaining
    self.purchase_amount - self.amount_spent
  end

  def hours_remaining
    (self.purchase_amount - self.amount_spent) / self.hourly_rate
  end

	def exceeds_remaining_hours_by?(hours=0)
			hours_over = hours - self.hours_remaining
			hours_over > 0 ? hours_over : 0
	end

  private
    
    def remove_contract_id_from_associated_time_entries
      self.time_entries.each do |time_entry|
        time_entry.contract_id = nil
        time_entry.save
      end
    end
end

plugins/contracts/app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  unloadable
  before_filter :find_project, :authorize, :only => [:index, :show, :new, :create, :edit, :update, :destroy,
                                                     :add_time_entries, :assoc_time_entries_with_contract]
  def index
    @project = Project.find(params[:project_id])
    @contracts = Contract.order("start_date ASC").where(:project_id => sub_projects_ids(@project))
    if not @project.name.include?('$')
      @contracts.delete_if{|c| c.project.name.include?('$')}
    end
    if params["active"] == "true"
      @contracts.delete_if{|c| c.end_date < Time.now and c.amount_remaining.to_i == 0}
    end

    if params["remaining"] == "true"
      @contracts.delete_if{|c| c.amount_remaining.to_i <= 0}
    end

    if params["pending"] == "true"
      @contracts.delete_if{|c| c.amount_remaining.to_i >= 0}
    end

    if not params["ignore"].nil?
      @contracts.delete_if{|c| c.title.include? params["ignore"]}
    end

    if params["user"]
      @contracts.delete_if{|c| not c or not c.title.include? params["user"]}
    end

=begin
    @total_purchased_dollars = @project.total_amount_purchased
    @total_purchased_hours   = @project.total_hours_purchased
    @total_remaining_dollars = @project.total_amount_remaining
    @total_remaining_hours   = @project.total_hours_remaining
=end
    @total_purchased_dollars = @contracts.sum { |contract| contract.purchase_amount }
    @total_purchased_hours   = @contracts.sum { |contract| contract.hours_purchased }
    @total_remaining_dollars = @contracts.sum { |contract| contract.amount_remaining }
    @total_remaining_hours   = @contracts.sum { |contract| contract.hours_remaining }
  end

  def sub_projects_ids project
    sub_projects = [project.id]
    project.children.each do |p|
      sub_projects += sub_projects_ids p
    end
    sub_projects.flatten
  end

  def all
    raise "FORBIDDEN" if not User.current
    if params["user"]
      @user = User.find_by_login params["user"]
    else
      @user = User.current
    end
    #@projects = @user.projects.select { |project| @user.roles_for_project(project).
    #                                                    first.permissions.
    #                                                    include?(:view_all_contracts_for_project) }
    @contracts = Contract.all.sort{|c1, c2| c1.start_date - c2.start_date}
    @contracts.flatten!
    begin
      if @user
        @contracts.delete_if{|c| not c or c.project.name.include?('$') or not c.title.include? @user.login}
      elsif params["user"]
        @contracts.delete_if{|c| not c or c.project.name.include?('$') or not c.title.include? params["user"]}
      end
    rescue
      puts "Ignorando"
    end
    if params["active"] == "true"
      @contracts.delete_if{|c| c.end_date < Time.now and c.amount_remaining.to_i == 0}
    end

    if params["remaining"] == "true"
      @contracts.delete_if{|c| c.amount_remaining.to_i <= 0}
    end

    if params["pending"] == "true"
      @contracts.delete_if{|c| c.amount_remaining.to_i >= 0}
    end

    if not params["ignore"].nil?
      @contracts.delete_if{|c| c.title.include? params["ignore"]}
    end

    @total_purchased_dollars = @contracts.sum { |contract| contract.purchase_amount }
    @total_purchased_hours   = @contracts.sum { |contract| contract.hours_purchased }
    @total_remaining_dollars = @contracts.sum { |contract| contract.amount_remaining }
    @total_remaining_hours   = @contracts.sum { |contract| contract.hours_remaining }

    render "index"
  end

  def new
    @contract = Contract.new
    @project = Project.find(params[:project_id])
    @project.contracts.empty? ? num = "001" : num = ("%03d" % (@project.contracts.last.id + 1))
    @new_title = @project.identifier + "_Dev_" + num
  end

  def create
    @contract = Contract.new(params[:contract])
    if @contract.save
      flash[:notice] = l(:text_contract_saved)
      redirect_to :action => "show", :id => @contract.id
    else
      flash[:error] = "* " + @contract.errors.full_messages.join("</br>* ")
      redirect_to :action => "new", :id => @contract.id
    end
  end

  def show
    @contract = Contract.find(params[:id])
    @time_entries = @contract.time_entries.order("spent_on DESC")
		@members= []
		@time_entries.each { |entry| @members.append(entry.user) unless @members.include?(entry.user) }
  end

  def edit
    @contract = Contract.find(params[:id])
    @projects = Project.all
  end

  def update
    @contract = Contract.find(params[:id])
    params[:contract].delete(:project_id)
    if @contract.update_attributes(params[:contract])
      flash[:notice] = l(:text_contract_updated)
      redirect_to :action => "show", :id => @contract.id
    else
      flash[:error] = "* " + @contract.errors.full_messages.join("</br>* ")
      redirect_to :action => "edit", :id => @contract.id
    end
  end

  def destroy
    @contract = Contract.find(params[:id])
    if @contract.destroy
      flash[:notice] = l(:text_contract_deleted)
      if !params[:project_id].nil?
        redirect_to :action => "index", :project_id => params[:project_id]
      else
        redirect_to :action => "all"
      end
    else
      redirect_to(:back)
    end
  end

  def add_time_entries
    @contract = Contract.find(params[:id])
    @project = @contract.project
    @time_entries = @contract.project.time_entries_for_all_descendant_projects.sort_by! { |entry| entry.spent_on }
  end

  def assoc_time_entries_with_contract
    @contract = Contract.find(params[:id])
    @project = @contract.project
    time_entries = params[:time_entries]
    if time_entries != nil
      time_entries.each do |time_entry|
        updated_time_entry = TimeEntry.find(time_entry.first)
        updated_time_entry.contract = @contract
        updated_time_entry.save
      end
    end
		flash[:error] = l(:text_hours_over_contract, :hours_over => l_hours(-1 * @contract.hours_remaining)) unless @contract.hours_remaining >= 0
    redirect_to "/projects/#{@contract.project.id}/contracts/#{@contract.id}"
  end

  def contabilizar_pagamentos
      valor = params[:valor]
      projeto_id = params[:project_id]
      contracts_id = params[:contract_id]
      contrato_id = Contract.find(contracts_id)

      [12,23].each do |activity|
          timeEntrie = TimeEntry.new :user => User.find(29), :activity => TimeEntryActivity.find(activity)
          timeEntrie.project_id = projeto_id
          timeEntrie.spent_on = Time.now
          timeEntrie.comments = "Pagamento"
          timeEntrie.hours = activity == 12 ? (-1 * valor.to_f) : valor
          timeEntrie.contract = contrato_id
          timeEntrie.save!
      end

      contrato = Contract.find(contracts_id)
      contrato.purchase_amount += valor.to_f
      contrato.description += "\r\n#{Time.now.strftime('%d/%m/%Y')} - R$ #{'%.2f' % valor}"
      contrato.save!

      #Contabilizando o valor no projeto contabil ou prestação de contas
      tipo = Project.find(projeto_id).custom_field_values.first
      if tipo
        timeEntry = TimeEntry.new :user => User.find(5)
        timeEntry.spent_on = Time.now
        timeEntry.comments = "Pagamento #{contrato.project.name}"
        timeEntry.hours = (-1 * valor.to_f)
        if tipo == 'contabil'
            timeEntry.activity = TimeEntryActivity.find(46)
            timeEntry.project_id = 48
            timeEntry.contract = Contract.find(93)
        else
            timeEntry.activity = TimeEntryActivity.find(46)
            timeEntry.project_id = 11
            timeEntry.contract = Contract.find(17)
        end
        timeEntry.save!
      end

      redirect_to "/projects/#{projeto_id}/contracts/#{contracts_id}"
  end

  def gerar_pagamentos(ano=nil, mes=nil)
      ano ||= Time.now.year
      mes ||= Time.now.month

      project_id = params[:project_id]
      contract_id = params[:contract_id]

      users = {
          4=>{:hora=>6.0, :ciee=>550}, #Lucão
          22=>{:hora=>8.0, :ciee=>550}, #Tafarel
          27=>{:hora=>7.5, :ciee=>0},   #Mitrut
          32=>{:hora=>7.5, :ciee=>550}  #Rafagnin
      }

      horas = {}
      time_entries = TimeEntry.on_project(Project.find(10), true).spent_between(Time.mktime(ano,mes-1,1), Time.mktime(ano,mes,1))
      time_entries.group_by{|t|t.user_id}.each{|a,c| horas[a] = c.sum{|k| k.hours}}

      users.each do |k,v|
          t = TimeEntry.new :user => User.find(5), :contract => Contract.find(81), :activity => TimeEntryActivity.find(47)
          t.project_id = 11
          t.spent_on = Time.mktime(ano, mes, 5)
          t.comments = "Pagamento #{User.find(k).name} #{mes-1}/#{ano}"
          t.hours = horas[k] * v[:hora] - v[:ciee]
          t.save!
      end

      if contract_id
        redirect_to "/projects/#{project_id}/contracts/#{contract_id}"
      else
        redirect_to "/projects/#{project_id}/contracts"
      end
  end

  def gerar_pagamentos_administrativo(ano=nil, mes=nil)
      ano ||= Time.now.year
      mes ||= Time.now.month
      project_id = params[:project_id]
      contract_id = params[:contract_id]

      {5 => 46, 10 => 47}.each do |k, c|
          ct = Contract.find(c)
          t = TimeEntry.new :user => User.find(5), :contract => Contract.find(81), :activity => TimeEntryActivity.find(50)
          t.project_id = 11
          t.spent_on = Time.mktime(ano, mes, 1)
          t.comments = "Administrativo #{User.find(k).name} #{mes -1}/#{ano}"
          t.hours = -ct.amount_remaining
          t.save!
          ct.description += "#{Time.now.strftime('%d/%m/%Y')} - R$#{- ct.amount_remaining}"
          ct.purchase_amount -= ct.amount_remaining
          ct.save!
      end

      if contract_id
        redirect_to "/projects/#{project_id}/contracts/#{contract_id}"
      else
        redirect_to "/projects/#{project_id}/contracts"
      end
  end

  private

  def find_project
    #@project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])

plugins/contracts/app/helpers/contracts_helper.rb
module ContractsHelper
end

plugins/contracts/app/views/contracts/_contracts_list.html.erb
<table class="contracts-list list">
  <thead>
    <tr>
      <th><%= l(:label_name) %></th>
      <th><%= l(:label_agreed_on) %></th>
      <th><%= l(:label_date_period) %></th>
      <th><%= l(:label_purchased) %></th>
      <% if (@project != nil) && (User.current.roles_for_project(@project).first.permissions.include?(:view_hourly_rate)) %>
        <th><%= l(:field_hourly_rate) %></th>
      <% end %>
      <th><%= l(:label_remaining) %></th>
      <th><%= l(:label_hours_worked) %></th>
      <th><%= l(:label_hours_left) %></th>
      <th><%= l(:label_contract) %></th>
      <th><%= l(:label_invoice) %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% @contracts.each do |contract| %>
    <tr class="<%= cycle("odd", "even") %>">
      <td>
        <%= link_to contract.title, "/projects/#{contract.project.identifier}/contracts/#{contract.id}" %>
      </td>
      <td><%= format_date(contract.agreement_date) %></td>
      <td><%= format_date(contract.start_date) + " - " + format_date(contract.end_date) %></td>
      <td><%= number_to_currency(contract.purchase_amount) %></td>
      <% if (@project != nil) && (User.current.roles_for_project(contract.project).first.permissions.include?(:view_hourly_rate)) %>
        <td><%= number_to_currency(contract.hourly_rate) %></td>
      <% end %>
      <td class="<%= (contract.amount_remaining > 0) ? "green" : "red" %>"><%= number_to_currency(contract.amount_remaining) %></td>
      <td><%= number_with_precision contract.hours_spent, :precision => 2 %></td>
      <td class="blue"><%= number_with_precision contract.hours_remaining, :precision => 2 %></td>
      <td>
        <% if !contract.contract_url.empty? %>
          <%= link_to image_tag("/images/files/text.png"), contract.contract_url %>
        <% end %>
      </td>
      <td>
        <% if !contract.invoice_url.empty? %>
          <%= link_to image_tag("/images/files/text.png"), contract.invoice_url%>
        <% end %>
      </td>
      <td>
        <% if User.current.roles_for_project(contract.project).first.permissions.include?(:edit_contracts) or User.current.admin? %>
          <%= link_to image_tag("/images/edit.png"), "/projects/#{contract.project.identifier}/contracts/#{contract.id}/edit", :title => l(:label_edit) %>
        <% end %>
      </td>
      <td>
        <% if User.current.roles_for_project(contract.project).first.permissions.include?(:delete_contracts) or User.current.admin? %>
            <%= link_to image_tag("/images/delete.png"), "/projects/#{contract.project.identifier}/contracts/#{contract.id}", :method => :delete, 
            :title => l(:label_delete), :confirm => l(:text_are_you_sure_delete_title, contract.title) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

plugins/contracts/app/views/contracts/_contracts_summary.html.erb
<table class="contracts-summary" >
  <tr>
    <td>
      <h3><%= l(:label_total_purchased) %></h3>
      <p class="bigbold"><%= number_to_currency(@total_purchased_dollars) %></p>
      <p><%= l(:label_or) %></p>
      <p class="bigbold">~<%= l_hours @total_purchased_hours %></p>
    </td>
    <td>
      <h3><%= l(:label_total_remaining) %></h3>
      <p class="<%= (@total_remaining_dollars > 0) ? "green" : "red" %> bigbold"><%= number_to_currency(@total_remaining_dollars) %></p>
      <p><%= l(:label_or) %></p>
      <p class="blue bigbold">~<%= l_hours @total_remaining_hours %></p>
    </td>
    <% if User.current.admin?%>
        <% if params[:project_id].to_i == 11 or params[:project_id].to_i == 48 or params[:project_id].eql? "prestacao_de_contas" or params[:project_id].eql? "contabil" %>
            <td>
                <h3>Administrativo</h3>
                <div class="provisionamentos">
                    <%= link_to "Provisionamentos", provisionamentos_index_path() %>
                </div>

                <div class="pagamento_estagiario">
                    <%= link_to "Pagamentos Estagiários", trainees_payments_index_path() %>
                </div>
            </td>
        <%end%>
    <%end%>
  </tr>
</table>
<br />

plugins/contracts/app/views/contracts/_time_entries_list.html.erb
<table class="time-entries-for-contract-list list">
  <thead>
    <tr>
      <th><%= l(:label_date) %></th>
      <th><%= l(:label_member) %></th>
      <th><%= l(:label_activity) %></th>
      <th><%= l(:label_contract) %></th>
      <th><%= l(:label_issue) %></th>
      <th><%= l(:label_comments) %></th>
      <th><%= l(:label_hours) %></th>
      <th>Total</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% @time_entries.each do |time_entry| %>
    <tr class="<%= cycle("odd", "even") %>">
      <td><%= format_date(time_entry.spent_on) %></td>
      <td><%= link_to time_entry.user.name, user_path(time_entry.user) %></td>
      <td><%= time_entry.activity.name %></td>
      <td><%= time_entry.contract.title %></td>
      <td><%= link_to time_entry.issue, issue_path(time_entry.issue) unless !time_entry.issue %></td>
      <td><%= time_entry.comments %></td>
      <td><%= time_entry.hours %></td>
      <td><%= (time_entry.cost != 0) ? time_entry.cost : time_entry.hours * (Rate.amount_for(time_entry.user, time_entry.project, time_entry.spent_on.strftime("%Y-%m-%d")) || @contract.hourly_rate) %></td>
      <td><%= link_to image_tag("/images/edit.png"), edit_time_entry_path(time_entry), :title => l(:label_edit) %></td>
      <td>
        <%= link_to image_tag("/images/delete.png"), time_entry_path(time_entry),
          :title => l(:label_delete), :confirm => l(:text_are_you_sure_delete_time_entry), :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

plugins/contracts/app/views/contracts/add_time_entries.html.erb
<h2><%= @contract.title %> - <%= l(:label_add_time_entries) %></h2>

<%= form_tag("/projects/#{@contract.project.identifier}/contracts/#{@contract.id}/assoc_time_entries_with_contract", :method => "put") do %>
  <table class="bulk-time-entries list">
    <thead>
      <tr>
        <th><%= l(:label_add_to_contract) %></th>
        <th><%= l(:label_date) %></th>
        <th><%= l(:label_current_contract) %></th>
        <th><%= l(:label_member) %></th>
        <th><%= l(:label_activity) %></th>
        <th><%= l(:label_issue) %></th>
        <th><%= l(:label_comments) %></th>
        <th><%= l(:label_hours) %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @time_entries.each do |time_entry| %>
      <tr class="<%= cycle("odd", "even") %>">
        <% ((time_entry.contract != nil) && (time_entry.contract.id == @contract.id)) ? if_disabled = true : if_disabled = false %>
        <% ((time_entry.contract != nil) && (time_entry.contract.id == @contract.id)) ? if_checked  = true : if_checked = false %>
        <td><%= check_box_tag("time_entries[#{time_entry.id}]", "1", if_checked, :disabled => if_disabled) %></td>
        <td><%= format_date(time_entry.spent_on) %></td>
        <td><%= time_entry.contract.title unless time_entry.contract == nil %></td>
        <td><%= link_to time_entry.user.name, user_path(time_entry.user) %></td>
        <td><%= time_entry.activity.name %></td>
        <td><%= link_to time_entry.issue, issue_path(time_entry.issue) unless !time_entry.issue %></td>
        <td><%= time_entry.comments %></td>
        <td><%= time_entry.hours %></td>
        <td><%= link_to image_tag("/images/edit.png"), edit_time_entry_path(time_entry), :title => l(:label_edit) %></td>
        <td>
          <%= link_to image_tag("/images/delete.png"), time_entry_path(time_entry),
            :title => l(:label_delete), 
            :confirm => l(:text_are_you_sure_delete_time_entry), 
            :method => :delete %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= submit_tag(l(:label_apply)) %>
<% end %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'contracts', :plugin => 'contracts' %>
<% end %>

plugins/contracts/app/views/contracts/edit.html.erb
<h2><%= l(:label_editing_contract) %> - <%= @contract.title %></h2>

<%= render "form" %>

plugins/contracts/app/views/contracts/index.html.erb
<div class="contextual">
  <% if (@project != nil) && (User.current.roles_for_project(@project).first.permissions.include?(:create_contracts)) %>
    <%= link_to l(:label_new_contract), "contracts/new", :class => 'icon icon-add' %>
  <% end %>
</div>

<h2><%= l(:label_contracts) %></h2>

<%= render 'contracts_summary' %>
<%= render 'contracts_list' %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'contracts', :plugin => 'contracts' %>
<% end %>

plugins/contracts/app/views/contracts/new.html.erb
<h2><%= l(:label_new_contract) %></h2>

<%= render 'form' %>

plugins/contracts/app/views/contracts/show.html.erb
<div class="contextual">
    <% if User.current.roles_for_project(@project).first.permissions.include?(:edit_contracts) %>
        <%= link_to l(:label_add_time_entries), "/projects/#{@project.identifier}/contracts/#{@contract.id}/add_time_entries" %>
    <% end %>
</div>


<h2>
    <%= @contract.title %>
    <% if User.current.roles_for_project(@project).first.permissions.include?(:edit_contracts) %>
        <%= link_to image_tag("/images/edit.png"), "#{@contract.id}/edit", :title => l(:label_edit) %>
    <% end %>
    <% if User.current.roles_for_project(@project).first.permissions.include?(:delete_contracts) %>
        <%= link_to image_tag("/images/delete.png"), "#{@contract.id}", :method => :delete,
            :title => l(:label_delete), :confirm => l(:text_are_you_sure_delete_title, @contract.title) %>
    <% end %>
</h2>
<% if User.current.admin? %>
    <div>
        <%= form_tag("/projects/#{@project.id}/contracts/#{@contract.id}/payment", :method => "post", :id => 'form_administrativo') %>
        <%= content_tag :label, "Valor: "%><%= content_tag(:input, "", :name => "valor") %><br />
        <%= submit_tag "Contabilizar"%>
    </div>

    <% if @project.id == 11 %>

        <hr/>
        <h3>Processos Administrativo</h3>
        <div class="provisionamentos">
            <%= link_to "Provisionamentos", provisionamentos_index_path() %>
        </div>

        <div class="pagamento_estagiario">
        <%= link_to "Pagamentos Estagiários", trainees_payments_index_path() %>
        </div>
        <hr/>
    <% end %>
<% end %>
<div>
	<table>
		<tr>
			<td colspan="2"><p><%= @contract.description.html_safe %></p></td>
		</tr>
		<tr>
			<td class="contract-summary-td">
				<table class="contract-summary list">
					<thead>
						<tr>
							<th><%= l(:field_agreement_date) %></th>
							<th><%= l(:label_date_period) %></th>
							<% if User.current.roles_for_project(@project).first.permissions.include?(:view_hourly_rate) %>
								<th><%= l(:field_hourly_rate) %></th>
							<% end %>
							<th><%= l(:label_amount_purchased) %></th>
							<% if !@contract.contract_url.empty? %>
								<th><%= l(:label_contract) %></th>
							<% end %>
							<% if !@contract.invoice_url.empty? %>
								<th><%= l(:label_invoice) %></th>
							<% end %>
                            <th><%= l(:label_remaining) %></th>
						</tr>
					</thead>
					<tbody>
						<tr class="<%= cycle("odd", "even") %>">
							<td><%= format_date(@contract.agreement_date)  %></td>
							<td><%= format_date(@contract.start_date) %> - <%= format_date(@contract.end_date)  %></td>
							<% if User.current.roles_for_project(@project).first.permissions.include?(:view_hourly_rate) %>
								<td><%= number_to_currency(@contract.hourly_rate) %></td>
							<% end %>
							<td><%= number_to_currency(@contract.purchase_amount) %></td>
							<% if !@contract.contract_url.empty? %>
									<td><%= link_to l(:label_view_contract), @contract.contract_url %></td>
							<% end %>
							<% if !@contract.invoice_url.empty? %>
									<td><%= link_to l(:label_view_invoice), @contract.invoice_url %></td>
							<% end %>
                             <td class="<%= (@contract.amount_remaining > 0) ? "green" : "red" %>"><%= number_to_currency(@contract.amount_remaining) %></td>
						</tr>
					</tbody>
				</table>
			</td>
			<td class="hours-summary-td">
				<table class="hours-summary list">
					<thead>
						<tr>
							<th><%= l(:label_members) %></th>
							<th><%= l(:label_hours) %></th>
						</tr>
					</thead>
					<tbody>
						<% @members.each do |member| %>
							<tr class="<%= cycle("odd", "even") %>">
								<td><%= member.name %></td>
								<td><%= @time_entries.select { |entry| entry.user == member }.sum { |entry| entry.hours } %></td>
							</tr>
						<% end %>
						<tr class="total-hours">
							<td></td>
							<td><%= @time_entries.sum { |entry| entry.hours } %></td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</table>
</div>

<h3><%= l(:label_time_entries) %></h3>
<%= render 'time_entries_list' %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'contracts', :plugin => 'contracts' %>
<% end %>